// <auto-generated />
using System;
using AdessoWorldLeague.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdessoWorldLeague.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("league")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdessoWorldLeague.Domain.Countries.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("iso_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.ToTable("countries", "league");

                    b.HasData(
                        new
                        {
                            Id = new Guid("37d83f25-109b-587d-ae37-55694ced4a05"),
                            IsoCode = "TR",
                            Name = "Türkiye"
                        },
                        new
                        {
                            Id = new Guid("9c4dbb6e-b6bc-530b-8876-fc5bdb557d4b"),
                            IsoCode = "DE",
                            Name = "Almanya"
                        },
                        new
                        {
                            Id = new Guid("cb4407c3-e25b-5ebf-9198-5195f35a91e3"),
                            IsoCode = "FR",
                            Name = "Fransa"
                        },
                        new
                        {
                            Id = new Guid("1a41e4e2-a53d-56fa-8644-e195e098b30b"),
                            IsoCode = "NL",
                            Name = "Hollanda"
                        },
                        new
                        {
                            Id = new Guid("52a55e9a-2500-55ae-ad07-5f1956c744d5"),
                            IsoCode = "PT",
                            Name = "Portekiz"
                        },
                        new
                        {
                            Id = new Guid("17dab60d-d721-56b3-a834-b7645828442d"),
                            IsoCode = "IT",
                            Name = "İtalya"
                        },
                        new
                        {
                            Id = new Guid("be44b6e4-3aa2-574f-ab5d-adc7b235a2a3"),
                            IsoCode = "ES",
                            Name = "İspanya"
                        },
                        new
                        {
                            Id = new Guid("564af7e8-ae13-5ecf-8728-2a21ace4df85"),
                            IsoCode = "BE",
                            Name = "Belçika"
                        });
                });

            modelBuilder.Entity("AdessoWorldLeague.Domain.Draws.Draw", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DrawnAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("drawn_at_utc");

                    b.Property<int>("GroupCount")
                        .HasColumnType("integer")
                        .HasColumnName("group_count");

                    b.HasKey("Id");

                    b.HasIndex("DrawnAtUtc")
                        .IsDescending();

                    b.ToTable("draws", "league");
                });

            modelBuilder.Entity("AdessoWorldLeague.Domain.Draws.DrawGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DrawId")
                        .HasColumnType("uuid")
                        .HasColumnName("draw_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("label");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex("DrawId", "Label")
                        .IsUnique();

                    b.ToTable("draw_groups", "league");
                });

            modelBuilder.Entity("AdessoWorldLeague.Domain.Draws.DrawGroupTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DrawGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("draw_group_id");

                    b.Property<Guid>("DrawId")
                        .HasColumnType("uuid")
                        .HasColumnName("draw_id");

                    b.Property<int>("PickNumber")
                        .HasColumnType("integer")
                        .HasColumnName("pick_number");

                    b.Property<int>("SelectionOrder")
                        .HasColumnType("integer")
                        .HasColumnName("selection_order");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("DrawGroupId", "SelectionOrder")
                        .IsUnique();

                    b.HasIndex("DrawId", "TeamId")
                        .IsUnique();

                    b.ToTable("draw_group_teams", "league");
                });

            modelBuilder.Entity("AdessoWorldLeague.Domain.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("teams", "league");

                    b.HasData(
                        new
                        {
                            Id = new Guid("31196768-f6e5-5860-98d7-a4e223ba01eb"),
                            CountryId = new Guid("37d83f25-109b-587d-ae37-55694ced4a05"),
                            Name = "Adesso İstanbul"
                        },
                        new
                        {
                            Id = new Guid("7a0c8e50-dc0f-539b-bfee-9beeda4e71a3"),
                            CountryId = new Guid("37d83f25-109b-587d-ae37-55694ced4a05"),
                            Name = "Adesso Ankara"
                        },
                        new
                        {
                            Id = new Guid("dbcb3903-5256-5fe9-b8ed-bfb20d0bf165"),
                            CountryId = new Guid("37d83f25-109b-587d-ae37-55694ced4a05"),
                            Name = "Adesso İzmir"
                        },
                        new
                        {
                            Id = new Guid("4fb9028e-2360-59d8-b186-915772af8511"),
                            CountryId = new Guid("37d83f25-109b-587d-ae37-55694ced4a05"),
                            Name = "Adesso Antalya"
                        },
                        new
                        {
                            Id = new Guid("1cf8670a-8e1e-5ea1-9439-1bb7519fce76"),
                            CountryId = new Guid("9c4dbb6e-b6bc-530b-8876-fc5bdb557d4b"),
                            Name = "Adesso Berlin"
                        },
                        new
                        {
                            Id = new Guid("a2c6e326-b2f5-5826-a54f-deed4e365804"),
                            CountryId = new Guid("9c4dbb6e-b6bc-530b-8876-fc5bdb557d4b"),
                            Name = "Adesso Frankfurt"
                        },
                        new
                        {
                            Id = new Guid("263f0560-f2d6-5263-9584-c79ecfe009d3"),
                            CountryId = new Guid("9c4dbb6e-b6bc-530b-8876-fc5bdb557d4b"),
                            Name = "Adesso Münih"
                        },
                        new
                        {
                            Id = new Guid("fa336017-2a50-54de-9818-61d8479fcf65"),
                            CountryId = new Guid("9c4dbb6e-b6bc-530b-8876-fc5bdb557d4b"),
                            Name = "Adesso Dortmund"
                        },
                        new
                        {
                            Id = new Guid("caf75675-3c55-58cc-994d-eef51cc2419d"),
                            CountryId = new Guid("cb4407c3-e25b-5ebf-9198-5195f35a91e3"),
                            Name = "Adesso Paris"
                        },
                        new
                        {
                            Id = new Guid("b34a64bf-2cbb-5221-8254-2a554622616a"),
                            CountryId = new Guid("cb4407c3-e25b-5ebf-9198-5195f35a91e3"),
                            Name = "Adesso Marsilya"
                        },
                        new
                        {
                            Id = new Guid("70ca042b-5dfe-59c3-ae55-118a9565dcfe"),
                            CountryId = new Guid("cb4407c3-e25b-5ebf-9198-5195f35a91e3"),
                            Name = "Adesso Nice"
                        },
                        new
                        {
                            Id = new Guid("299ad215-7b39-55bc-90df-82c8c3502a36"),
                            CountryId = new Guid("cb4407c3-e25b-5ebf-9198-5195f35a91e3"),
                            Name = "Adesso Lyon"
                        },
                        new
                        {
                            Id = new Guid("05b22c2b-0613-5d2c-a6d5-3f423e343b16"),
                            CountryId = new Guid("1a41e4e2-a53d-56fa-8644-e195e098b30b"),
                            Name = "Adesso Amsterdam"
                        },
                        new
                        {
                            Id = new Guid("a600e592-8bb0-5837-a35b-643d63ac776e"),
                            CountryId = new Guid("1a41e4e2-a53d-56fa-8644-e195e098b30b"),
                            Name = "Adesso Rotterdam"
                        },
                        new
                        {
                            Id = new Guid("cafbd70f-3de0-55fe-9d20-041b49bbeaf0"),
                            CountryId = new Guid("1a41e4e2-a53d-56fa-8644-e195e098b30b"),
                            Name = "Adesso Lahey"
                        },
                        new
                        {
                            Id = new Guid("677e29b4-5b5d-533e-ad5c-d0991724b4d9"),
                            CountryId = new Guid("1a41e4e2-a53d-56fa-8644-e195e098b30b"),
                            Name = "Adesso Eindhoven"
                        },
                        new
                        {
                            Id = new Guid("6e8def07-d547-5453-8d91-2fb1acf71b4d"),
                            CountryId = new Guid("52a55e9a-2500-55ae-ad07-5f1956c744d5"),
                            Name = "Adesso Lisbon"
                        },
                        new
                        {
                            Id = new Guid("f9efcffe-4d6b-5f04-9520-012c0012ebd3"),
                            CountryId = new Guid("52a55e9a-2500-55ae-ad07-5f1956c744d5"),
                            Name = "Adesso Porto"
                        },
                        new
                        {
                            Id = new Guid("6d41b3b5-05f1-5214-a719-bd0733233918"),
                            CountryId = new Guid("52a55e9a-2500-55ae-ad07-5f1956c744d5"),
                            Name = "Adesso Braga"
                        },
                        new
                        {
                            Id = new Guid("0920f705-2765-51a9-a3b8-550f5ebef4cd"),
                            CountryId = new Guid("52a55e9a-2500-55ae-ad07-5f1956c744d5"),
                            Name = "Adesso Coimbra"
                        },
                        new
                        {
                            Id = new Guid("efaf34c6-b7c4-5801-b796-7283f6a4d7b4"),
                            CountryId = new Guid("17dab60d-d721-56b3-a834-b7645828442d"),
                            Name = "Adesso Roma"
                        },
                        new
                        {
                            Id = new Guid("6d050f2f-8dfc-51a8-9c03-7f796f926e39"),
                            CountryId = new Guid("17dab60d-d721-56b3-a834-b7645828442d"),
                            Name = "Adesso Milano"
                        },
                        new
                        {
                            Id = new Guid("d3fc2a84-63fb-58e6-ad08-1d9d9ce9b19e"),
                            CountryId = new Guid("17dab60d-d721-56b3-a834-b7645828442d"),
                            Name = "Adesso Venedik"
                        },
                        new
                        {
                            Id = new Guid("014dcc59-d254-5eb1-acbe-faf893c09f99"),
                            CountryId = new Guid("17dab60d-d721-56b3-a834-b7645828442d"),
                            Name = "Adesso Napoli"
                        },
                        new
                        {
                            Id = new Guid("904b1362-f0c3-5b31-9512-c08518e474d2"),
                            CountryId = new Guid("be44b6e4-3aa2-574f-ab5d-adc7b235a2a3"),
                            Name = "Adesso Sevilla"
                        },
                        new
                        {
                            Id = new Guid("0f5e15f6-817f-5828-9352-94e3223d6c36"),
                            CountryId = new Guid("be44b6e4-3aa2-574f-ab5d-adc7b235a2a3"),
                            Name = "Adesso Madrid"
                        },
                        new
                        {
                            Id = new Guid("61847517-744b-5075-a3cf-1c26749d8705"),
                            CountryId = new Guid("be44b6e4-3aa2-574f-ab5d-adc7b235a2a3"),
                            Name = "Adesso Barselona"
                        },
                        new
                        {
                            Id = new Guid("d8140222-2a55-57f1-8142-5c3abc1728ec"),
                            CountryId = new Guid("be44b6e4-3aa2-574f-ab5d-adc7b235a2a3"),
                            Name = "Adesso Granada"
                        },
                        new
                        {
                            Id = new Guid("819d826c-62e9-5ee3-8c45-91f43c54719d"),
                            CountryId = new Guid("564af7e8-ae13-5ecf-8728-2a21ace4df85"),
                            Name = "Adesso Brüksel"
                        },
                        new
                        {
                            Id = new Guid("56e2818b-c9ce-5f0a-926b-c226ff68eb26"),
                            CountryId = new Guid("564af7e8-ae13-5ecf-8728-2a21ace4df85"),
                            Name = "Adesso Brugge"
                        },
                        new
                        {
                            Id = new Guid("714acb33-72e2-5341-8a99-ca9e18d7b3af"),
                            CountryId = new Guid("564af7e8-ae13-5ecf-8728-2a21ace4df85"),
                            Name = "Adesso Gent"
                        },
                        new
                        {
                            Id = new Guid("e6ca3b36-86f3-5b7c-8ae4-417655d7d5ce"),
                            CountryId = new Guid("564af7e8-ae13-5ecf-8728-2a21ace4df85"),
                            Name = "Adesso Anvers"
                        });
                });

            modelBuilder.Entity("AdessoWorldLeague.Domain.Draws.Draw", b =>
                {
                    b.OwnsOne("AdessoWorldLeague.Domain.Draws.ParticipantName", "DrawnBy", b1 =>
                        {
                            b1.Property<Guid>("DrawId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("drawn_by_first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("drawn_by_last_name");

                            b1.HasKey("DrawId");

                            b1.ToTable("draws", "league");

                            b1.WithOwner()
                                .HasForeignKey("DrawId");
                        });

                    b.Navigation("DrawnBy")
                        .IsRequired();
                });

            modelBuilder.Entity("AdessoWorldLeague.Domain.Draws.DrawGroup", b =>
                {
                    b.HasOne("AdessoWorldLeague.Domain.Draws.Draw", null)
                        .WithMany("Groups")
                        .HasForeignKey("DrawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdessoWorldLeague.Domain.Draws.DrawGroupTeam", b =>
                {
                    b.HasOne("AdessoWorldLeague.Domain.Draws.DrawGroup", null)
                        .WithMany("Teams")
                        .HasForeignKey("DrawGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdessoWorldLeague.Domain.Teams.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AdessoWorldLeague.Domain.Teams.Team", b =>
                {
                    b.HasOne("AdessoWorldLeague.Domain.Countries.Country", "Country")
                        .WithMany("Teams")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AdessoWorldLeague.Domain.Countries.Country", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("AdessoWorldLeague.Domain.Draws.Draw", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("AdessoWorldLeague.Domain.Draws.DrawGroup", b =>
                {
                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
