<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AdessoWorldLeague.Domain\AdessoWorldLeague.Domain.csproj" />
    <ProjectReference Include="..\..\src\AdessoWorldLeague.Application\AdessoWorldLeague.Application.csproj" />
    <ProjectReference Include="..\..\src\AdessoWorldLeague.Infrastructure\AdessoWorldLeague.Infrastructure.csproj" />
  </ItemGroup>

</Project>
