<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AdessoWorldLeague.Api\AdessoWorldLeague.Api.csproj" />
    <ProjectReference Include="..\..\src\AdessoWorldLeague.Infrastructure\AdessoWorldLeague.Infrastructure.csproj" />
  </ItemGroup>

</Project>
